In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv(r"C:\Users\luyil\ihealth\datasets\preproc\decoded_data.csv")
data.head()

,Unnamed: 0,payer,insurer_paid_amt_mean,insurer_paid_amt_sum,member_paid_amt_mean,member_paid_amt_sum,total_paid_amt_mean,total_paid_amt_sum,row_id,service_year,...,svc_code,svc_code_type,svc_code_ctg,svc_code_ctg_desc,clm_cnt,member_months,total_paid_amt_median,insurer_paid_amt_median,member_paid_amt_median,service
0,0,MEDICARE,0.00,0.00,0.00,0.00,0.00,0.00,3127575.0,2010.0,...,G8482,CPT/HCPCS,999.0,HCPCS Level II codes not classified,21.0,180.0,0.00,0.00,0.00,Procedures / Professional Services
1,1,COMMERCIAL,258.94,3366.29,71.67,931.73,330.61,4298.02,2888025.0,2010.0,...,76705,CPT/HCPCS,196.0,Ultrasound - Abdomen/retroperitoneum - Diagnostic,24.0,137.0,328.00,284.33,43.26,Radiology
2,2,MINNESOTA HEALTH CARE PROGRAMS,225.33,28392.81,0.00,0.00,225.33,28392.81,2878775.0,2010.0,...,A0425,CPT/HCPCS,239.0,"Transportation - Patient, provider, equipment",205.0,1321.0,81.83,81.83,0.00,Ambulance and Other Transport Services and Sup...
3,3,COMMERCIAL,1311.12,14422.37,32.76,360.45,1343.89,14782.82,3142946.0,2010.0,...,C8929,CPT/HCPCS,193.0,Ultrasound - Heart (echocardiogram) - Diagnostic,11.0,132.0,1681.67,1674.97,0.00,Outpatient PPS
4,4,MEDICARE,2922.00,46752.03,1102.31,17637.01,4024.31,64389.04,3127585.0,2010.0,...,J0690,CPT/HCPCS,240.0,"Medications (injections, infusions, other forms)",22.0,192.0,0.00,0.00,0.00,Drugs Administered Other than Oral Method

In [3]:
data.dtypes

Unnamed: 0                   int64
payer                       object
insurer_paid_amt_mean      float64
insurer_paid_amt_sum       float64
member_paid_amt_mean       float64
member_paid_amt_sum        float64
total_paid_amt_mean        float64
total_paid_amt_sum         float64
row_id                     float64
service_year               float64
county_code                float64
county_name                 object
age_group_code             float64
age_group_name              object
sex                         object
unique_member_cnt          float64
svc_code                    object
svc_code_type               object
svc_code_ctg               float64
svc_code_ctg_desc           object
clm_cnt                    float64
member_months              float64
total_paid_amt_median      float64
insurer_paid_amt_median    float64
member_paid_amt_median     float64
service                     object
dtype: object

Vriables we will drop: 
- "Unnamed: 0": useless index number. 
- "row_id": another useless id data. 
- "svc_code" and "svc_code_type": we already decode these variables to "service" feature.

In [5]:
drop_data_1 = ["Unnamed: 0","row_id","svc_code","svc_code_type"]
dropped_data = data.drop(drop_data_1,axis=1)
dropped_data.head()

,payer,insurer_paid_amt_mean,insurer_paid_amt_sum,member_paid_amt_mean,member_paid_amt_sum,total_paid_amt_mean,total_paid_amt_sum,service_year,county_code,county_name,...,sex,unique_member_cnt,svc_code_ctg,svc_code_ctg_desc,clm_cnt,member_months,total_paid_amt_median,insurer_paid_amt_median,member_paid_amt_median,service
0,MEDICARE,0.00,0.00,0.00,0.00,0.00,0.00,2010.0,23.0,Chippewa,...,M,15.0,999.0,HCPCS Level II codes not classified,21.0,180.0,0.00,0.00,0.00,Procedures / Professional Services
1,COMMERCIAL,258.94,3366.29,71.67,931.73,330.61,4298.02,2010.0,9.0,Benton,...,M,13.0,196.0,Ultrasound - Abdomen/retroperitoneum - Diagnostic,24.0,137.0,328.00,284.33,43.26,Radiology
2,MINNESOTA HEALTH CARE PROGRAMS,225.33,28392.81,0.00,0.00,225.33,28392.81,2010.0,7.0,Beltrami,...,M,126.0,239.0,"Transportation - Patient, provider, equipment",205.0,1321.0,81.83,81.83,0.00,Ambulance and Other Transport Services and Sup...
3,COMMERCIAL,1311.12,14422.37,32.76,360.45,1343.89,14782.82,2010.0,25.0,Chisago,...,F,11.0,193.0,Ultrasound - Heart (echocardiogram) - Diagnostic,11.0,132.0,1681.67,1674.97,0.00,Outpatient PPS
4,MEDICARE,2922.00,46752.03,1102.31,17637.01,4024.31,64389.04,2010.0,23.0,Chippewa,...,M,16.0,240.0,"Medications (injections, infusions, other forms)",22.0,192.0,0.00,0.00,0.00,Drugs Administered Other than Oral Method

It very useful for us to know the proportion that insurer paid and member paid. 
- insurer_paid_prop = insurer_paid_amt / total_paid_amt
- member_paid_prop = member_paid_amt / total_paid_amt

In [6]:
print(dropped_data.shape)

new_columns = [
    "insurer_paid_sum_prop",
    "insurer_paid_mean_prop",
    "insurer_paid_median_prop",
    "member_paid_sum_prop",
    "member_paid_mean_prop",
    "member_paid_median_prop"
]

upper_vars = [
    "insurer_paid_amt_sum",
    "insurer_paid_amt_mean",
    "insurer_paid_amt_median",
    "member_paid_amt_sum",
    "member_paid_amt_mean",
    "member_paid_amt_median"
]

lower_vards = [
    "total_paid_amt_sum",
    "total_paid_amt_mean",
    "total_paid_amt_median",
    "total_paid_amt_sum",
    "total_paid_amt_mean",
    "total_paid_amt_median"
]

for i in range(0, len(new_columns)):
    dropped_data[new_columns[i]] = dropped_data[upper_vars[i]] / dropped_data[lower_vards[i]]

print(dropped_data.shape)

(6872085, 22)
(6872085, 28)

In [7]:
dropped_data.head()

,payer,insurer_paid_amt_mean,insurer_paid_amt_sum,member_paid_amt_mean,member_paid_amt_sum,total_paid_amt_mean,total_paid_amt_sum,service_year,county_code,county_name,...,total_paid_amt_median,insurer_paid_amt_median,member_paid_amt_median,service,insurer_paid_sum_prop,insurer_paid_mean_prop,insurer_paid_median_prop,member_paid_sum_prop,member_paid_mean_prop,member_paid_median_prop
0,MEDICARE,0.00,0.00,0.00,0.00,0.00,0.00,2010.0,23.0,Chippewa,...,0.00,0.00,0.00,Procedures / Professional Services,NaN,NaN,NaN,NaN,NaN,NaN
1,COMMERCIAL,258.94,3366.29,71.67,931.73,330.61,4298.02,2010.0,9.0,Benton,...,328.00,284.33,43.26,Radiology,0.783219,0.783219,0.866860,0.216781,0.216781,0.13189
2,MINNESOTA HEALTH CARE PROGRAMS,225.33,28392.81,0.00,0.00,225.33,28392.81,2010.0,7.0,Beltrami,...,81.83,81.83,0.00,Ambulance and Other Transport Services and Sup...,1.000000,1.000000,1.000000,0.000000,0.000000,0.00000
3,COMMERCIAL,1311.12,14422.37,32.76,360.45,1343.89,14782.82,2010.0,25.0,Chisago,...,1681.67,1674.97,0.00,Outpatient PPS,0.975617,0.975616,0.996016,0.024383,0.024377,0.00000
4,MEDICARE,2922.00,46752.03,1102.31,17637.01,4024.31,64389.04,2010.0,23.0,Chippewa,...,0.00,0.00,0.00,Drugs Administered Other than Oral Method,0.726087,0.726087,NaN,0.273913,0.273913,NaN

We discovered some of the data are NA or NUll.

In [8]:
dropped_data.isna().mean()

payer                       0.000000
insurer_paid_amt_mean       0.000000
insurer_paid_amt_sum        0.000000
member_paid_amt_mean        0.000000
member_paid_amt_sum         0.000000
total_paid_amt_mean         0.000000
total_paid_amt_sum          0.000000
service_year                0.000000
county_code                 0.000000
county_name                 0.000000
age_group_code              0.000000
age_group_name              0.000000
sex                         0.000000
unique_member_cnt           0.000000
svc_code_ctg                0.000000
svc_code_ctg_desc           0.000000
clm_cnt                     0.000000
member_months               0.000000
total_paid_amt_median       0.000000
insurer_paid_amt_median     0.000000
member_paid_amt_median      0.000000
service                     0.000000
insurer_paid_sum_prop       0.023182
insurer_paid_mean_prop      0.024941
insurer_paid_median_prop    0.199538
member_paid_sum_prop        0.023182
member_paid_mean_prop       0.024941
member_paid_median_prop     0.199538
dtype: float64

In [9]:
dropped_data.isnull().mean()

payer                       0.000000
insurer_paid_amt_mean       0.000000
insurer_paid_amt_sum        0.000000
member_paid_amt_mean        0.000000
member_paid_amt_sum         0.000000
total_paid_amt_mean         0.000000
total_paid_amt_sum          0.000000
service_year                0.000000
county_code                 0.000000
county_name                 0.000000
age_group_code              0.000000
age_group_name              0.000000
sex                         0.000000
unique_member_cnt           0.000000
svc_code_ctg                0.000000
svc_code_ctg_desc           0.000000
clm_cnt                     0.000000
member_months               0.000000
total_paid_amt_median       0.000000
insurer_paid_amt_median     0.000000
member_paid_amt_median      0.000000
service                     0.000000
insurer_paid_sum_prop       0.023182
insurer_paid_mean_prop      0.024941
insurer_paid_median_prop    0.199538
member_paid_sum_prop        0.023182
member_paid_mean_prop       0.024941
member_paid_median_prop     0.199538
dtype: float64

Approximate ~20% of the data are null for "insurer_paid_median_prop" and "member_paid_median_prop"; we choose not to use these features. For the rest of the data there're ~2% are null, we just directly drop those NA value.

In [10]:
# drop features
print(dropped_data.shape)
dropped_data_2 = dropped_data.drop(["insurer_paid_median_prop","member_paid_median_prop"],axis=1)
# drop NA
dropped_data_2 = dropped_data_2.dropna()
print(dropped_data_2.shape)

(6872085, 28)
(6700685, 26)

In [11]:
dropped_data_2.isna().mean()

payer                      0.0
insurer_paid_amt_mean      0.0
insurer_paid_amt_sum       0.0
member_paid_amt_mean       0.0
member_paid_amt_sum        0.0
total_paid_amt_mean        0.0
total_paid_amt_sum         0.0
service_year               0.0
county_code                0.0
county_name                0.0
age_group_code             0.0
age_group_name             0.0
sex                        0.0
unique_member_cnt          0.0
svc_code_ctg               0.0
svc_code_ctg_desc          0.0
clm_cnt                    0.0
member_months              0.0
total_paid_amt_median      0.0
insurer_paid_amt_median    0.0
member_paid_amt_median     0.0
service                    0.0
insurer_paid_sum_prop      0.0
insurer_paid_mean_prop     0.0
member_paid_sum_prop       0.0
member_paid_mean_prop      0.0
dtype: float64

In [12]:
dropped_data_2.head()

,payer,insurer_paid_amt_mean,insurer_paid_amt_sum,member_paid_amt_mean,member_paid_amt_sum,total_paid_amt_mean,total_paid_amt_sum,service_year,county_code,county_name,...,clm_cnt,member_months,total_paid_amt_median,insurer_paid_amt_median,member_paid_amt_median,service,insurer_paid_sum_prop,insurer_paid_mean_prop,member_paid_sum_prop,member_paid_mean_prop
1,COMMERCIAL,258.94,3366.29,71.67,931.73,330.61,4298.02,2010.0,9.0,Benton,...,24.0,137.0,328.00,284.33,43.26,Radiology,0.783219,0.783219,0.216781,0.216781
2,MINNESOTA HEALTH CARE PROGRAMS,225.33,28392.81,0.00,0.00,225.33,28392.81,2010.0,7.0,Beltrami,...,205.0,1321.0,81.83,81.83,0.00,Ambulance and Other Transport Services and Sup...,1.000000,1.000000,0.000000,0.000000
3,COMMERCIAL,1311.12,14422.37,32.76,360.45,1343.89,14782.82,2010.0,25.0,Chisago,...,11.0,132.0,1681.67,1674.97,0.00,Outpatient PPS,0.975617,0.975616,0.024383,0.024377
4,MEDICARE,2922.00,46752.03,1102.31,17637.01,4024.31,64389.04,2010.0,23.0,Chippewa,...,22.0,192.0,0.00,0.00,0.00,Drugs Administered Other than Oral Method,0.726087,0.726087,0.273913,0.273913
5,COMMERCIAL,270.29,4054.36,164.76,2471.52,435.05,6525.88,2010.0,9.0,Benton,...,36.0,172.0,389.13,133.34,87.72,Radiology,0.621274,0.621285,0.378726,0.378715

It's also will be helpful if we find the average operations per member by:
average_ops_cnt = clm_cnt / unique_member_cnt

In [13]:
dropped_data_2["average_ops_cnt"] = dropped_data_2["clm_cnt"]/dropped_data_2["unique_member_cnt"]
dropped_data_2.isna().mean(), dropped_data_2.shape

(payer                      0.0
 insurer_paid_amt_mean      0.0
 insurer_paid_amt_sum       0.0
 member_paid_amt_mean       0.0
 member_paid_amt_sum        0.0
 total_paid_amt_mean        0.0
 total_paid_amt_sum         0.0
 service_year               0.0
 county_code                0.0
 county_name                0.0
 age_group_code             0.0
 age_group_name             0.0
 sex                        0.0
 unique_member_cnt          0.0
 svc_code_ctg               0.0
 svc_code_ctg_desc          0.0
 clm_cnt                    0.0
 member_months              0.0
 total_paid_amt_median      0.0
 insurer_paid_amt_median    0.0
 member_paid_amt_median     0.0
 service                    0.0
 insurer_paid_sum_prop      0.0
 insurer_paid_mean_prop     0.0
 member_paid_sum_prop       0.0
 member_paid_mean_prop      0.0
 average_ops_cnt            0.0
 dtype: float64,
 (6700685, 27))

Final drops:
- "svc_code_ctg": no description, we won't use it I guessed.

In [14]:
final_data = dropped_data_2.drop(["svc_code_ctg"],axis=1)
final_data.shape

(6700685, 26)

In [15]:
# save it!
final_data.to_csv(r"C:\Users\luyil\ihealth\datasets\preproc\final_dataset.csv")